<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Vjezba.Model.csproj" />
  </ItemGroup>

  <!-- EF Core DbContext / migrations will be added here later -->

</Project>
